apiVersion: batch/v1
kind: CronJob
metadata:
  name: okalt
  namespace: flask-app-internal
spec:
  schedule: "* * * * *"  # This schedule is set to run every minute. Adjust this according to your needs.
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: web
            image: containers.cisco.com/thousandeyes-it/flask-app-test:latest
            resources:
              requests:
                memory: "128Mi"  # Adjust the memory request based on your requirements
              limits:
                memory: "256Mi"  # Adjust the memory limit based on your requirements
            securityContext:
              runAsNonRoot: true
              runAsUser: 1000
              runAsGroup: 2000
              fsGroup: 2000
          imagePullSecrets:
          - name: thousandeyes-it-justins-helloworld-pull-secret
          restartPolicy: OnFailure